import { ArrowRight, Basket, CheckCircle, Database, FolderSimple, Info, LockSimple, MagnifyingGlass, Plus, ShieldCheck, User, WarningCircle, WifiSlash } from '@phosphor-icons/react'
import { useMemo, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useGrocea } from '../../app/grocea-context'
import { AppShell, BackHeader, BrandHeader, EmptyState, PageHeading } from '../../shared/ui/AppShell'

export function MoreScreen() {
  const { profile, categories, ingredients } = useGrocea()
  return <AppShell navigation><BrandHeader /><main className="screen-content"><PageHeading title="More" subtitle="Preferences and catalog tools" /><section className="profile-summary"><span>{profile.displayName[0].toUpperCase()}</span><div><strong>{profile.displayName}</strong><small>Local profile · Metric</small></div><Link className="icon-button" to="/profile" aria-label="Open profile"><ArrowRight /></Link></section><section className="menu-list"><Link to="/ingredients"><span className="menu-icon"><Basket /></span><span><strong>Ingredient catalog</strong><small>{ingredients.length} ingredients</small></span><ArrowRight /></Link><Link to="/categories"><span className="menu-icon"><FolderSimple /></span><span><strong>Categories</strong><small>{categories.length} global and custom categories</small></span><ArrowRight /></Link><Link to="/profile"><span className="menu-icon"><User /></span><span><strong>Profile</strong><small>Cooking defaults and local preferences</small></span><ArrowRight /></Link><Link to="/system-states"><span className="menu-icon"><Database /></span><span><strong>System states</strong><small>Reusable UI state reference</small></span><ArrowRight /></Link></section><div className="info-banner"><ShieldCheck /><span><strong>Stored on this device</strong><br />No account or cloud sync in Phase 0.</span></div></main></AppShell>
}

export function CategoriesScreen() {
  const { categories, ingredients, createCategory } = useGrocea(); const [query, setQuery] = useState(''); const [adding, setAdding] = useState(false); const [name, setName] = useState('')
  const shown = useMemo(() => categories.filter(category => category.name.toLowerCase().includes(query.trim().toLowerCase())), [categories, query])
  function submit(event: FormEvent) { event.preventDefault(); const value = name.trim(); if (!value || categories.some(category => category.name.toLowerCase() === value.toLowerCase())) return; createCategory(value); setName(''); setAdding(false) }
  return <AppShell navigation><BrandHeader /><main className="screen-content"><PageHeading title="Categories" subtitle={`${categories.filter(item => item.scope === 'global').length} global · ${categories.filter(item => item.scope === 'custom').length} yours`} action={<button className="button primary compact" onClick={() => setAdding(true)}><Plus />New</button>} />{adding && <form className="inline-create" onSubmit={submit}><label><span className="sr-only">Category name</span><input autoFocus value={name} onChange={event => setName(event.target.value)} placeholder="Category name" /></label><button className="button primary" disabled={!name.trim()}>Add</button><button className="button secondary" type="button" onClick={() => setAdding(false)}>Cancel</button></form>}<label className="search-field"><MagnifyingGlass /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search categories" /><span className="sr-only">Search categories</span></label>{(['global', 'custom'] as const).map(scope => <section className="category-section" key={scope}><div className="section-label"><strong>{scope === 'global' ? 'GLOBAL' : 'YOURS'}</strong><span>{scope === 'global' ? 'READ-ONLY' : 'CUSTOM'}</span></div><div className="data-list">{shown.filter(item => item.scope === scope).map(category => <div className="category-row" key={category.id}><span className="menu-icon"><FolderSimple /></span><span><strong>{category.name}</strong><small>{ingredients.filter(item => item.categoryId === category.id).length} ingredients</small></span>{scope === 'global' ? <LockSimple /> : <span className="tag">Yours</span>}</div>)}</div></section>)}<div className="info-banner"><Info /><span>Deleting a category would require reassigning its ingredients first.</span></div></main></AppShell>
}

export function ProfileScreen() {
  const { profile, updateProfile } = useGrocea(); const navigate = useNavigate(); const [name, setName] = useState(profile.displayName); const [servings, setServings] = useState(profile.preferredServings); const [saved, setSaved] = useState(false)
  function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; updateProfile(name.trim(), servings); setSaved(true) }
  return <AppShell><BackHeader title="Profile" eyebrow="Local preferences" /><form className="form-screen wide-form" onSubmit={submit}><section className="profile-summary large"><span>{name.trim()[0]?.toUpperCase() || '?'}</span><div><strong>{name.trim() || 'Your profile'}</strong><small>Local profile · Created 12 Jul 2026</small></div></section>{saved && <div className="success-notice" role="status">Profile preferences saved.</div>}<section className="form-section"><h2>Profile</h2><label className="field-group"><span>Display name</span><input value={name} onChange={event => setName(event.target.value)} maxLength={120} /></label><label className="field-group"><span>Measurement system</span><select value="metric" disabled><option>Metric</option></select></label></section><section className="form-section"><h2>Cooking defaults</h2><div className="stepper-row"><span><strong>Preferred servings</strong><small>Pre-fills recipe and cook flows</small></span><div className="stepper"><button type="button" onClick={() => setServings(Math.max(1, servings - 1))}>−</button><strong>{servings}</strong><button type="button" onClick={() => setServings(Math.min(12, servings + 1))}>+</button></div></div></section><section className="data-card"><Database /><span><strong>Stored on this device</strong><small>No account or cloud sync in Phase 0</small></span></section><div className="info-banner"><ShieldCheck /><span>Your profile is intentionally minimal for the MVP.</span></div><div className="form-actions"><button className="button secondary" type="button" onClick={() => navigate(-1)}>Cancel</button><button className="button primary" disabled={!name.trim()}><CheckCircle />Save changes</button></div></form></AppShell>
}

export function SystemStatesScreen() {
  return <AppShell><BackHeader title="Shared system states" eyebrow="Reusable UI reference" /><main className="screen-content"><PageHeading title="System states" subtitle="Consistent recovery and confirmation patterns." /><div className="states-grid"><StateCard title="Loading" label="Skeleton"><div className="skeleton"><i /><i /><i /><i /></div><small>Preserve layout. Block actions.</small></StateCard><StateCard title="Empty" label="First use"><EmptyState icon={Basket} title="Pantry is empty" message="Add your first ingredient to start tracking stock." /><small>One clear recovery action.</small></StateCard><StateCard title="Error" label="Recoverable"><div className="warning-banner danger"><WarningCircle /><span><strong>Couldn’t load pantry</strong><small>Check your connection and try again.</small></span></div><button className="button secondary">Try again</button><small>Explain cause. Keep retry nearby.</small></StateCard><StateCard title="Offline" label="Read-only"><div className="info-banner"><WifiSlash /><span><strong>You’re offline</strong><br />Showing saved data from 10:42.</span></div><button className="button secondary" disabled>Add stock unavailable</button><small>No offline mutations in Phase 0.</small></StateCard><StateCard title="Success" label="Confirmation"><div className="success-notice"><CheckCircle />Stock updated. Added 1 kg to Basmati rice.</div><small>Confirm result, not only completion.</small></StateCard></div></main></AppShell>
}
function StateCard({ title, label, children }: { title: string; label: string; children: React.ReactNode }) { return <article className="state-card"><header><strong>{title}</strong><span>{label}</span></header><div>{children}</div></article> }
